spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: arda
    password: 12345
    url: jdbc:postgresql://localhost:5432/mydatabase
  application:
    name: casestudy
  jpa:
    hibernate:
      ddl-auto: update
logging:
  file:
    name: logs/App.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    c.l.c.logging.PassengerAspectLogging: INFO
    com.lydiatech.casestudy.logging.PassengerAspectLogging: INFO